<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exposed.proto

namespace GPBMetadata;

class Exposed
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0010a0d6578706f7365642e70726f746f120550726f746f22520a1050" .
            "726f746f4578706f7365644c69737412180a10626174636852656c656173" .
            "6554696d6518012001280312240a076578706f73656418022003280b3213" .
            "2e50726f746f2e50726f746f4578706f736565222c0a0c50726f746f4578" .
            "706f736565120b0a036b657918022001280c120f0a076b65794461746518" .
            "0320012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

