<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace GPBMetadata;

class File
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2020a0a66696c652e70726f746f120550726f746f223e0a0446696c65" .
            "121d0a0668656164657218012001280b320d2e50726f746f2e4865616465" .
            "7212170a036b657918022003280b320a2e50726f746f2e4b6579226b0a06" .
            "48656164657212160a0e737461727454696d657374616d70180120012803" .
            "12140a0c656e6454696d657374616d70180220012803120e0a0672656769" .
            "6f6e18032001280912100a0862617463684e756d18042001280512110a09" .
            "626174636853697a6518052001280522680a034b6579120f0a076b657944" .
            "61746118012001280c121a0a12726f6c6c696e6753746172744e756d6265" .
            "7218022001280d12150a0d726f6c6c696e67506572696f6418032001280d" .
            "121d0a157472616e736d697373696f6e5269736b4c6576656c1804200128" .
            "05620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

