<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Time window of keys in this file based on arrival to server, in UTC.
     *
     * Generated from protobuf field <code>int64 startTimestamp = 1;</code>
     */
    private $startTimestamp = 0;
    /**
     * Generated from protobuf field <code>int64 endTimestamp = 2;</code>
     */
    private $endTimestamp = 0;
    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     */
    private $region = '';
    /**
     * E.g., Batch 2 of 10
     *
     * Generated from protobuf field <code>int32 batchNum = 4;</code>
     */
    private $batchNum = 0;
    /**
     * Generated from protobuf field <code>int32 batchSize = 5;</code>
     */
    private $batchSize = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $startTimestamp
     *           Time window of keys in this file based on arrival to server, in UTC.
     *     @type int|string $endTimestamp
     *     @type string $region
     *           Region for which these keys came from (e.g., country)
     *     @type int $batchNum
     *           E.g., Batch 2 of 10
     *     @type int $batchSize
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\File::initOnce();
        parent::__construct($data);
    }

    /**
     * Time window of keys in this file based on arrival to server, in UTC.
     *
     * Generated from protobuf field <code>int64 startTimestamp = 1;</code>
     * @return int|string
     */
    public function getStartTimestamp()
    {
        return $this->startTimestamp;
    }

    /**
     * Time window of keys in this file based on arrival to server, in UTC.
     *
     * Generated from protobuf field <code>int64 startTimestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->startTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 endTimestamp = 2;</code>
     * @return int|string
     */
    public function getEndTimestamp()
    {
        return $this->endTimestamp;
    }

    /**
     * Generated from protobuf field <code>int64 endTimestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->endTimestamp = $var;

        return $this;
    }

    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * E.g., Batch 2 of 10
     *
     * Generated from protobuf field <code>int32 batchNum = 4;</code>
     * @return int
     */
    public function getBatchNum()
    {
        return $this->batchNum;
    }

    /**
     * E.g., Batch 2 of 10
     *
     * Generated from protobuf field <code>int32 batchNum = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->batchNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 batchSize = 5;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batchSize;
    }

    /**
     * Generated from protobuf field <code>int32 batchSize = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->batchSize = $var;

        return $this;
    }

}

