<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.Key</code>
 */
class Key extends \Google\Protobuf\Internal\Message
{
    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes keyData = 1;</code>
     */
    private $keyData = '';
    /**
     * Interval number when the key's EKRollingPeriod started.
     *
     * Generated from protobuf field <code>uint32 rollingStartNumber = 2;</code>
     */
    private $rollingStartNumber = 0;
    /**
     * Number of 10-minute windows between key rolling.
     *
     * Generated from protobuf field <code>uint32 rollingPeriod = 3;</code>
     */
    private $rollingPeriod = 0;
    /**
     * Risk of transmission associated with the person this key came from.
     *
     * Generated from protobuf field <code>int32 transmissionRiskLevel = 4;</code>
     */
    private $transmissionRiskLevel = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyData
     *           Key of infected user
     *     @type int $rollingStartNumber
     *           Interval number when the key's EKRollingPeriod started.
     *     @type int $rollingPeriod
     *           Number of 10-minute windows between key rolling.
     *     @type int $transmissionRiskLevel
     *           Risk of transmission associated with the person this key came from.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\File::initOnce();
        parent::__construct($data);
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes keyData = 1;</code>
     * @return string
     */
    public function getKeyData()
    {
        return $this->keyData;
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes keyData = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyData($var)
    {
        GPBUtil::checkString($var, False);
        $this->keyData = $var;

        return $this;
    }

    /**
     * Interval number when the key's EKRollingPeriod started.
     *
     * Generated from protobuf field <code>uint32 rollingStartNumber = 2;</code>
     * @return int
     */
    public function getRollingStartNumber()
    {
        return $this->rollingStartNumber;
    }

    /**
     * Interval number when the key's EKRollingPeriod started.
     *
     * Generated from protobuf field <code>uint32 rollingStartNumber = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingStartNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->rollingStartNumber = $var;

        return $this;
    }

    /**
     * Number of 10-minute windows between key rolling.
     *
     * Generated from protobuf field <code>uint32 rollingPeriod = 3;</code>
     * @return int
     */
    public function getRollingPeriod()
    {
        return $this->rollingPeriod;
    }

    /**
     * Number of 10-minute windows between key rolling.
     *
     * Generated from protobuf field <code>uint32 rollingPeriod = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingPeriod($var)
    {
        GPBUtil::checkUint32($var);
        $this->rollingPeriod = $var;

        return $this;
    }

    /**
     * Risk of transmission associated with the person this key came from.
     *
     * Generated from protobuf field <code>int32 transmissionRiskLevel = 4;</code>
     * @return int
     */
    public function getTransmissionRiskLevel()
    {
        return $this->transmissionRiskLevel;
    }

    /**
     * Risk of transmission associated with the person this key came from.
     *
     * Generated from protobuf field <code>int32 transmissionRiskLevel = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTransmissionRiskLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->transmissionRiskLevel = $var;

        return $this;
    }

}

