<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exposed.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.ProtoExposedList</code>
 */
class ProtoExposedList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 batchReleaseTime = 1;</code>
     */
    private $batchReleaseTime = 0;
    /**
     * Generated from protobuf field <code>repeated .Proto.ProtoExposee exposed = 2;</code>
     */
    private $exposed;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $batchReleaseTime
     *     @type \Proto\ProtoExposee[]|\Google\Protobuf\Internal\RepeatedField $exposed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Exposed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 batchReleaseTime = 1;</code>
     * @return int|string
     */
    public function getBatchReleaseTime()
    {
        return $this->batchReleaseTime;
    }

    /**
     * Generated from protobuf field <code>int64 batchReleaseTime = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBatchReleaseTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->batchReleaseTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.ProtoExposee exposed = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExposed()
    {
        return $this->exposed;
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.ProtoExposee exposed = 2;</code>
     * @param \Proto\ProtoExposee[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExposed($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ProtoExposee::class);
        $this->exposed = $arr;

        return $this;
    }

}

