<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exposed.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.ProtoExposee</code>
 */
class ProtoExposee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>int64 keyDate = 3;</code>
     */
    private $keyDate = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type int|string $keyDate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Exposed::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 keyDate = 3;</code>
     * @return int|string
     */
    public function getKeyDate()
    {
        return $this->keyDate;
    }

    /**
     * Generated from protobuf field <code>int64 keyDate = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeyDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->keyDate = $var;

        return $this;
    }

}

