<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemporaryExposureKeyFormat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.SignatureInfo</code>
 */
class SignatureInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Apple App Store Application Bundle ID
     *
     * Generated from protobuf field <code>string app_bundle_id = 1;</code>
     */
    private $app_bundle_id = '';
    /**
     * Android App package name
     *
     * Generated from protobuf field <code>string android_package = 2;</code>
     */
    private $android_package = '';
    /**
     * Key version for rollovers
     *
     * Generated from protobuf field <code>string verification_key_version = 3;</code>
     */
    private $verification_key_version = '';
    /**
     * Generated from protobuf field <code>string verification_key_id = 4;</code>
     */
    private $verification_key_id = '';
    /**
     * E.g. ECDSA using a p-256 curve and SHA-256 as a hash function
     *
     * Generated from protobuf field <code>string signature_algorithm = 5;</code>
     */
    private $signature_algorithm = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_bundle_id
     *           Apple App Store Application Bundle ID
     *     @type string $android_package
     *           Android App package name
     *     @type string $verification_key_version
     *           Key version for rollovers
     *     @type string $verification_key_id
     *     @type string $signature_algorithm
     *           E.g. ECDSA using a p-256 curve and SHA-256 as a hash function
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TemporaryExposureKeyFormat::initOnce();
        parent::__construct($data);
    }

    /**
     * Apple App Store Application Bundle ID
     *
     * Generated from protobuf field <code>string app_bundle_id = 1;</code>
     * @return string
     */
    public function getAppBundleId()
    {
        return $this->app_bundle_id;
    }

    /**
     * Apple App Store Application Bundle ID
     *
     * Generated from protobuf field <code>string app_bundle_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppBundleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_bundle_id = $var;

        return $this;
    }

    /**
     * Android App package name
     *
     * Generated from protobuf field <code>string android_package = 2;</code>
     * @return string
     */
    public function getAndroidPackage()
    {
        return $this->android_package;
    }

    /**
     * Android App package name
     *
     * Generated from protobuf field <code>string android_package = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAndroidPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->android_package = $var;

        return $this;
    }

    /**
     * Key version for rollovers
     *
     * Generated from protobuf field <code>string verification_key_version = 3;</code>
     * @return string
     */
    public function getVerificationKeyVersion()
    {
        return $this->verification_key_version;
    }

    /**
     * Key version for rollovers
     *
     * Generated from protobuf field <code>string verification_key_version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVerificationKeyVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->verification_key_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verification_key_id = 4;</code>
     * @return string
     */
    public function getVerificationKeyId()
    {
        return $this->verification_key_id;
    }

    /**
     * Generated from protobuf field <code>string verification_key_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVerificationKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->verification_key_id = $var;

        return $this;
    }

    /**
     * E.g. ECDSA using a p-256 curve and SHA-256 as a hash function
     *
     * Generated from protobuf field <code>string signature_algorithm = 5;</code>
     * @return string
     */
    public function getSignatureAlgorithm()
    {
        return $this->signature_algorithm;
    }

    /**
     * E.g. ECDSA using a p-256 curve and SHA-256 as a hash function
     *
     * Generated from protobuf field <code>string signature_algorithm = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSignatureAlgorithm($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature_algorithm = $var;

        return $this;
    }

}

