<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemporaryExposureKeyFormat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.TEKSignatureList</code>
 */
class TEKSignatureList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Proto.TEKSignature signatures = 1;</code>
     */
    private $signatures;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\TEKSignature[]|\Google\Protobuf\Internal\RepeatedField $signatures
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TemporaryExposureKeyFormat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.TEKSignature signatures = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.TEKSignature signatures = 1;</code>
     * @param \Proto\TEKSignature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\TEKSignature::class);
        $this->signatures = $arr;

        return $this;
    }

}

