<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemporaryExposureKeyFormat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.TemporaryExposureKey</code>
 */
class TemporaryExposureKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     */
    private $key_data = '';
    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2;</code>
     */
    private $transmission_risk_level = 0;
    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     */
    private $rolling_start_interval_number = 0;
    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     */
    private $rolling_period = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_data
     *           Key of infected user
     *     @type int $transmission_risk_level
     *           Varying risk associated with a key depending on diagnosis method
     *     @type int $rolling_start_interval_number
     *           The interval number since epoch for which a key starts
     *     @type int $rolling_period
     *           Increments of 10 minutes describing how long a key is valid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TemporaryExposureKeyFormat::initOnce();
        parent::__construct($data);
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     * @return string
     */
    public function getKeyData()
    {
        return $this->key_data;
    }

    /**
     * Key of infected user
     *
     * Generated from protobuf field <code>bytes key_data = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyData($var)
    {
        GPBUtil::checkString($var, False);
        $this->key_data = $var;

        return $this;
    }

    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2;</code>
     * @return int
     */
    public function getTransmissionRiskLevel()
    {
        return $this->transmission_risk_level;
    }

    /**
     * Varying risk associated with a key depending on diagnosis method
     *
     * Generated from protobuf field <code>int32 transmission_risk_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTransmissionRiskLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->transmission_risk_level = $var;

        return $this;
    }

    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     * @return int
     */
    public function getRollingStartIntervalNumber()
    {
        return $this->rolling_start_interval_number;
    }

    /**
     * The interval number since epoch for which a key starts
     *
     * Generated from protobuf field <code>int32 rolling_start_interval_number = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingStartIntervalNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->rolling_start_interval_number = $var;

        return $this;
    }

    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     * @return int
     */
    public function getRollingPeriod()
    {
        return $this->rolling_period;
    }

    /**
     * Increments of 10 minutes describing how long a key is valid
     *
     * Generated from protobuf field <code>int32 rolling_period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRollingPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->rolling_period = $var;

        return $this;
    }

}

