<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemporaryExposureKeyFormat.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.TemporaryExposureKeyExport</code>
 */
class TemporaryExposureKeyExport extends \Google\Protobuf\Internal\Message
{
    /**
     * Time window of keys in this batch based on arrival to server, in UTC seconds
     *
     * Generated from protobuf field <code>fixed64 start_timestamp = 1;</code>
     */
    private $start_timestamp = 0;
    /**
     * Generated from protobuf field <code>fixed64 end_timestamp = 2;</code>
     */
    private $end_timestamp = 0;
    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     */
    private $region = '';
    /**
     * E.g., File 2 in batch size of 10. Ordinal, 1-based numbering.
     *
     * Generated from protobuf field <code>int32 batch_num = 4;</code>
     */
    private $batch_num = 0;
    /**
     * Generated from protobuf field <code>int32 batch_size = 5;</code>
     */
    private $batch_size = 0;
    /**
     * Information about associated signatures
     *
     * Generated from protobuf field <code>repeated .Proto.SignatureInfo signature_infos = 6;</code>
     */
    private $signature_infos;
    /**
     * The TemporaryExposureKeys themselves
     *
     * Generated from protobuf field <code>repeated .Proto.TemporaryExposureKey keys = 7;</code>
     */
    private $keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $start_timestamp
     *           Time window of keys in this batch based on arrival to server, in UTC seconds
     *     @type int|string $end_timestamp
     *     @type string $region
     *           Region for which these keys came from (e.g., country)
     *     @type int $batch_num
     *           E.g., File 2 in batch size of 10. Ordinal, 1-based numbering.
     *     @type int $batch_size
     *     @type \Proto\SignatureInfo[]|\Google\Protobuf\Internal\RepeatedField $signature_infos
     *           Information about associated signatures
     *     @type \Proto\TemporaryExposureKey[]|\Google\Protobuf\Internal\RepeatedField $keys
     *           The TemporaryExposureKeys themselves
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TemporaryExposureKeyFormat::initOnce();
        parent::__construct($data);
    }

    /**
     * Time window of keys in this batch based on arrival to server, in UTC seconds
     *
     * Generated from protobuf field <code>fixed64 start_timestamp = 1;</code>
     * @return int|string
     */
    public function getStartTimestamp()
    {
        return $this->start_timestamp;
    }

    /**
     * Time window of keys in this batch based on arrival to server, in UTC seconds
     *
     * Generated from protobuf field <code>fixed64 start_timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 end_timestamp = 2;</code>
     * @return int|string
     */
    public function getEndTimestamp()
    {
        return $this->end_timestamp;
    }

    /**
     * Generated from protobuf field <code>fixed64 end_timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_timestamp = $var;

        return $this;
    }

    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Region for which these keys came from (e.g., country)
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * E.g., File 2 in batch size of 10. Ordinal, 1-based numbering.
     *
     * Generated from protobuf field <code>int32 batch_num = 4;</code>
     * @return int
     */
    public function getBatchNum()
    {
        return $this->batch_num;
    }

    /**
     * E.g., File 2 in batch size of 10. Ordinal, 1-based numbering.
     *
     * Generated from protobuf field <code>int32 batch_num = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 batch_size = 5;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batch_size;
    }

    /**
     * Generated from protobuf field <code>int32 batch_size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_size = $var;

        return $this;
    }

    /**
     * Information about associated signatures
     *
     * Generated from protobuf field <code>repeated .Proto.SignatureInfo signature_infos = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatureInfos()
    {
        return $this->signature_infos;
    }

    /**
     * Information about associated signatures
     *
     * Generated from protobuf field <code>repeated .Proto.SignatureInfo signature_infos = 6;</code>
     * @param \Proto\SignatureInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatureInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\SignatureInfo::class);
        $this->signature_infos = $arr;

        return $this;
    }

    /**
     * The TemporaryExposureKeys themselves
     *
     * Generated from protobuf field <code>repeated .Proto.TemporaryExposureKey keys = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * The TemporaryExposureKeys themselves
     *
     * Generated from protobuf field <code>repeated .Proto.TemporaryExposureKey keys = 7;</code>
     * @param \Proto\TemporaryExposureKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\TemporaryExposureKey::class);
        $this->keys = $arr;

        return $this;
    }

}

